channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=23.3.1
- pip:
  - mlflow==2.12.2
  - cloudpickle==2.2.1
  - configparser==5.0.2
  - lz4==4.3.2
  - psutil==5.9.0
  - scikit-learn==1.2.2
  - typing-extensions==4.9.0
name: mlflow-env
